In [1]:
from main import *
import warnings
warnings.filterwarnings('ignore')

In [34]:
# Loading data frame
path='data/Titanic-Dataset.csv'
df=load_data(path)
print(df.shape)
df.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df=drop_columns(df,['PassengerId'])
df.shape

(891, 11)

In [16]:
# drop missing target 
df=drop_missing_target(df,'Survived')
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
# check missing 
result=check_missing(df)
print(result)
df.shape

   column_name  total_missing  percentage_missing
0     Survived              0                0.00
1       Pclass              0                0.00
2         Name              0                0.00
3          Sex              0                0.00
4          Age            177               19.87
5        SibSp              0                0.00
6        Parch              0                0.00
7       Ticket              0                0.00
8         Fare              0                0.00
9        Cabin            687               77.10
10    Embarked              2                0.22

(891, 11)

In [18]:
# drop missing above threshold
df=drop_threshold(df,result,30)
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [19]:
report2=check_missing(df)
print(report2)

  column_name  total_missing  percentage_missing
0    Survived              0                0.00
1      Pclass              0                0.00
2        Name              0                0.00
3         Sex              0                0.00
4         Age            177               19.87
5       SibSp              0                0.00
6       Parch              0                0.00
7      Ticket              0                0.00
8        Fare              0                0.00
9    Embarked              2                0.22

In [20]:
# info
col_report=detect_column_types(df,'Survived')
print(col_report)

{'numerical': ['Age', 'Fare'], 'categorical': ['Name', 'Sex', 'Embarked'], 'datetime': [], 'mixed': ['Ticket'], 'encoded_categorical': ['Pclass', 'SibSp', 'Parch'], 'target': {'name': 'Survived', 'type': 'numerical'}}

In [21]:
x,y=prepare_x_y(df,'Survived',col_report['mixed'],col_report['datetime'])
print(x.head())
print(y.head())

   Pclass                                               Name     Sex   Age  \
0       3                            Braund, Mr. Owen Harris    male  22.0
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2       3                             Heikkinen, Miss. Laina  female  26.0
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4       3                           Allen, Mr. William Henry    male  35.0

   SibSp  Parch     Fare Embarked
0      1      0   7.2500        S
1      1      0  71.2833        C
2      0      0   7.9250        S
3      1      0  53.1000        S
4      0      0   8.0500        S
0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [22]:
print(col_report['numerical'])
trans=get_valid_transformers(x,col_report['numerical'])
print(trans)

['Age', 'Fare']
[('passthrough', 'passthrough'), ('yeojohnson', PowerTransformer()), ('log', FunctionTransformer(func=<ufunc 'log1p'>)), ('sqrt', FunctionTransformer(func=<ufunc 'sqrt'>))]

In [23]:
tranformers=get_valid_transformers(df,col_report['numerical'])

In [ ]:
result_df=run_experiments(x,y,col_report['numerical'],col_report['categorical'],col_report['encoded_categorical'],numerical_imputers,categorical_imputers,encoders,tranformers,scalers)

[1/1296] mean | most_frequent | onehot | passthrough | passthrough →

r2 = 0.8025 ± 0.0255
[2/1296] mean | most_frequent | onehot | passthrough | standard → r2 = 0.8036 ± 0.0244
[3/1296] mean | most_frequent | onehot | passthrough | minmax → r2 = 0.7980 ± 0.0219
[4/1296] mean | most_frequent | onehot | passthrough | robust → r2 = 0.8036 ± 0.0244
[5/1296] mean | most_frequent | onehot | passthrough | maxabs → r2 = 0.7980 ± 0.0219
[6/1296] mean | most_frequent | onehot | passthrough | mean_normalisation → r2 = 0.7957 ± 0.0257
[7/1296] mean | most_frequent | onehot | yeojohnson | passthrough → r2 = 0.7957 ± 0.0277
[8/1296] mean | most_frequent | onehot | yeojohnson | standard → r2 = 0.7957 ± 0.0277
[9/1296] mean | most_frequent | onehot | yeojohnson | minmax → r2 = 0.8002 ± 0.0226
[10/1296] mean | most_frequent | onehot | yeojohnson | robust → r2 = 0.7969 ± 0.0269
[11/1296] mean | most_frequent | onehot | yeojohnson | maxabs → r2 = 0.7957 ± 0.0263
[12/1296] mean | most_frequent | onehot | yeojohnson | mean_normalisation → r2 = 0.7980 ± 0.0277
[13/1296] mean | most_frequent | onehot | log | passthrough → r2 = 0.8092 ± 0.0244
[14/1296] mean | most_frequent | onehot | log | standard → r2 = 0.8070 ± 0.0253
[15/1296] mean | most_frequent | onehot | log | minmax → r2 = 0.8114 ± 0.0294
[16/1296] mean | most_frequent | onehot | log | robust → r2 = 0.8070 ± 0.0253
[17/1296] mean | most_frequent | onehot | log | maxabs → r2 = 0.8126 ± 0.0267
[18/1296] mean | most_frequent | onehot | log | mean_normalisation → r2 = 0.8058 ± 0.0303
[19/1296] mean | most_frequent | onehot | sqrt | passthrough → r2 = 0.8047 ± 0.0283
[20/1296] mean | most_frequent | onehot | sqrt | standard → r2 = 0.8047 ± 0.0283
[21/1296] mean | most_frequent | onehot | sqrt | minmax → r2 = 0.8036 ± 0.0265
[22/1296] mean | most_frequent | onehot | sqrt | robust → r2 = 0.8058 ± 0.0277
[23/1296] mean | most_frequent | onehot | sqrt | maxabs → r2 = 0.8036 ± 0.0265
[24/1296] mean | most_frequent | onehot | sqrt | mean_normalisation → r2 = 0.8025 ± 0.0264
[25/1296] mean | most_frequent | ordinal | passthrough | passthrough → r2 = 0.7901 ± 0.0198
[26/1296] mean | most_frequent | ordinal | passthrough | standard → r2 = 0.7901 ± 0.0192
[27/1296] mean | most_frequent | ordinal | passthrough | minmax → r2 = 0.7935 ± 0.0209
[28/1296] mean | most_frequent | ordinal | passthrough | robust → r2 = 0.7901 ± 0.0192
[29/1296] mean | most_frequent | ordinal | passthrough | maxabs → r2 = 0.7935 ± 0.0209
[30/1296] mean | most_frequent | ordinal | passthrough | mean_normalisation → r2 = 0.7924 ± 0.0199
[31/1296] mean | most_frequent | ordinal | yeojohnson | passthrough → r2 = 0.7912 ± 0.0210
[32/1296] mean | most_frequent | ordinal | yeojohnson | standard → r2 = 0.7912 ± 0.0210
[33/1296] mean | most_frequent | ordinal | yeojohnson | minmax → r2 = 0.7924 ± 0.0226
[34/1296] mean | most_frequent | ordinal | yeojohnson | robust → r2 = 0.7912 ± 0.0210
[35/1296] mean | most_frequent | ordinal | yeojohnson | maxabs → r2 = 0.7935 ± 0.0191
[36/1296] mean | most_frequent | ordinal | yeojohnson | mean_normalisation → r2 = 0.7912 ± 0.0235
[37/1296] mean | most_frequent | ordinal | log | passthrough → r2 = 0.8069 ± 0.0233
[38/1296] mean | most_frequent | ordinal | log | standard → r2 = 0.8069 ± 0.0230
[39/1296] mean | most_frequent | ordinal | log | minmax → r2 = 0.8013 ± 0.0162
[40/1296] mean | most_frequent | ordinal | log | robust → r2 = 0.8081 ± 0.0224
[41/1296] mean | most_frequent | ordinal | log | maxabs → r2 = 0.7980 ± 0.0187
[42/1296] mean | most_frequent | ordinal | log | mean_normalisation → r2 = 0.8036 ± 0.0244
[43/1296] mean | most_frequent | ordinal | sqrt | passthrough → r2 = 0.8025 ± 0.0216
[44/1296] mean | most_frequent | ordinal | sqrt | standard → r2 = 0.8025 ± 0.0216
[45/1296] mean | most_frequent | ordinal | sqrt | minmax → r2 = 0.7968 ± 0.0197
[46/1296] mean | most_frequent | ordinal | sqrt | robust → r2 = 0.8036 ± 0.0205
[47/1296] mean | most_frequent | ordinal | sqrt | maxabs → r2 = 0.7980 ± 0.0192
[48/1296] mean | most_frequent | ordinal | sqrt | mean_normalisation → r2 = 0.7968 ± 0.0210
[49/1296] mean | missing_cat | onehot | passthrough | passthrough → r2 = 0.8013 ± 0.0235
[50/1296] mean | missing_cat | onehot | passthrough | standard → r2 = 0.8036 ± 0.0217
[51/1296] mean | missing_cat | onehot | passthrough | minmax → r2 = 0.7980 ± 0.0219
[52/1296] mean | missing_cat | onehot | passthrough | robust → r2 = 0.8047 ± 0.0237
[53/1296] mean | missing_cat | onehot | passthrough | maxabs → r2 = 0.7980 ± 0.0219
[54/1296] mean | missing_cat | onehot | passthrough | mean_normalisation → r2 = 0.7957 ± 0.0257
[55/1296] mean | missing_cat | onehot | yeojohnson | passthrough → r2 = 0.7957 ± 0.0277
[56/1296] mean | missing_cat | onehot | yeojohnson | standard → r2 = 0.7957 ± 0.0277
[57/1296] mean | missing_cat | onehot | yeojohnson | minmax → r2 = 0.8002 ± 0.0226
[58/1296] mean | missing_cat | onehot | yeojohnson | robust → r2 = 0.7969 ± 0.0269
[59/1296] mean | missing_cat | onehot | yeojohnson | maxabs → r2 = 0.7980 ± 0.0244
[60/1296] mean | missing_cat | onehot | yeojohnson | mean_normalisation → r2 = 0.7980 ± 0.0277
[61/1296] mean | missing_cat | onehot | log | passthrough → r2 = 0.8081 ± 0.0244
[62/1296] mean | missing_cat | onehot | log | standard → r2 = 0.8070 ± 0.0253
[63/1296] mean | missing_cat | onehot | log | minmax → r2 = 0.8114 ± 0.0294
[64/1296] mean | missing_cat | onehot | log | robust → r2 = 0.8058 ± 0.0265
[65/1296] mean | missing_cat | onehot | log | maxabs → r2 = 0.8126 ± 0.0267
[66/1296] mean | missing_cat | onehot | log | mean_normalisation → r2 = 0.8058 ± 0.0303
[67/1296] mean | missing_cat | onehot | sqrt | passthrough → r2 = 0.8036 ± 0.0264
[68/1296] mean | missing_cat | onehot | sqrt | standard → r2 = 0.8036 ± 0.0264
[69/1296] mean | missing_cat | onehot | sqrt | minmax → r2 = 0.8036 ± 0.0265
[70/1296] mean | missing_cat | onehot | sqrt | robust → r2 = 0.8047 ± 0.0258
[71/1296] mean | missing_cat | onehot | sqrt | maxabs → r2 = 0.8036 ± 0.0265
[72/1296] mean | missing_cat | onehot | sqrt | mean_normalisation → r2 = 0.8025 ± 0.0264
[73/1296] mean | missing_cat | ordinal | passthrough | passthrough → r2 = 0.7912 ± 0.0187
[74/1296] mean | missing_cat | ordinal | passthrough | standard → r2 = 0.7901 ± 0.0192
[75/1296] mean | missing_cat | ordinal | passthrough | minmax → r2 = 0.7946 ± 0.0213
[76/1296] mean | missing_cat | ordinal | passthrough | robust → r2 = 0.7901 ± 0.0192
[77/1296] mean | missing_cat | ordinal | passthrough | maxabs → r2 = 0.7935 ± 0.0209
[78/1296] mean | missing_cat | ordinal | passthrough | mean_normalisation → r2 = 0.7924 ± 0.0199
[79/1296] mean | missing_cat | ordinal | yeojohnson | passthrough → r2 = 0.7912 ± 0.0210
[80/1296] mean | missing_cat | ordinal | yeojohnson | standard → r2 = 0.7912 ± 0.0210
[81/1296] mean | missing_cat | ordinal | yeojohnson | minmax → r2 = 0.7924 ± 0.0226
[82/1296] mean | missing_cat | ordinal | yeojohnson | robust → r2 = 0.7912 ± 0.0210
[83/1296] mean | missing_cat | ordinal | yeojohnson | maxabs → r2 = 0.7935 ± 0.0191
[84/1296] mean | missing_cat | ordinal | yeojohnson | mean_normalisation → r2 = 0.7912 ± 0.0235
[85/1296] mean | missing_cat | ordinal | log | passthrough → r2 = 0.8069 ± 0.0233
[86/1296] mean | missing_cat | ordinal | log | standard → r2 = 0.8069 ± 0.0230
[87/1296] mean | missing_cat | ordinal | log | minmax → r2 = 0.8013 ± 0.0162
[88/1296] mean | missing_cat | ordinal | log | robust → r2 = 0.8081 ± 0.0224
[89/1296] mean | missing_cat | ordinal | log | maxabs → r2 = 0.7980 ± 0.0187
[90/1296] mean | missing_cat | ordinal | log | mean_normalisation → r2 = 0.8036 ± 0.0244
[91/1296] mean | missing_cat | ordinal | sqrt | passthrough → r2 = 0.8036 ± 0.0205
[92/1296] mean | missing_cat | ordinal | sqrt | standard → r2 = 0.8036 ± 0.0205
[93/1296] mean | missing_cat | ordinal | sqrt | minmax → r2 = 0.7968 ± 0.0197
[94/1296] mean | missing_cat | ordinal | sqrt | robust → r2 = 0.8036 ± 0.0205
[95/1296] mean | missing_cat | ordinal | sqrt | maxabs → r2 = 0.7980 ± 0.0192
[96/1296] mean | missing_cat | ordinal | sqrt | mean_normalisation → r2 = 0.7968 ± 0.0210
[97/1296] mean | Random_category | onehot | passthrough | passthrough → FAILED —
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 613, in fit
    Xt = self._fit(X, y, routed_params, raw_params=params)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 547, in _fit
    X, fitted_transformer = fit_transform_one_cached(
                            ~~~~~~~~~~~~~~~~~~~~~~~~^
        cloned_transformer,
        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        params=step_params,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\joblib\memory.py", line 326, in __call__
    return self.func(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 1484, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1029, in fit_transform
    return self._hstack(list(Xs), n_samples=n_samples)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1213, in _hstack
    raise ValueError(
    ...<5 lines>...
    )
ValueError: Concatenating DataFrames from the transformer's output lead to an inconsistent number of samples. The output may have Pandas Indexes that do not match, or that transformers are returning number of samples which are not the same as the number input samples.

[98/1296] mean | Random_category | onehot | passthrough | standard → FAILED —
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 613, in fit
    Xt = self._fit(X, y, routed_params, raw_params=params)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 547, in _fit
    X, fitted_transformer = fit_transform_one_cached(
                            ~~~~~~~~~~~~~~~~~~~~~~~~^
        cloned_transformer,
        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        params=step_params,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\joblib\memory.py", line 326, in __call__
    return self.func(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 1484, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1029, in fit_transform
    return self._hstack(list(Xs), n_samples=n_samples)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1213, in _hstack
    raise ValueError(
    ...<5 lines>...
    )
ValueError: Concatenating DataFrames from the transformer's output lead to an inconsistent number of samples. The output may have Pandas Indexes that do not match, or that transformers are returning number of samples which are not the same as the number input samples.

[99/1296] mean | Random_category | onehot | passthrough | minmax → FAILED —
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 613, in fit
    Xt = self._fit(X, y, routed_params, raw_params=params)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 547, in _fit
    X, fitted_transformer = fit_transform_one_cached(
                            ~~~~~~~~~~~~~~~~~~~~~~~~^
        cloned_transformer,
        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        params=step_params,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\joblib\memory.py", line 326, in __call__
    return self.func(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 1484, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1029, in fit_transform
    return self._hstack(list(Xs), n_samples=n_samples)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1213, in _hstack
    raise ValueError(
    ...<5 lines>...
    )
ValueError: Concatenating DataFrames from the transformer's output lead to an inconsistent number of samples. The output may have Pandas Indexes that do not match, or that transformers are returning number of samples which are not the same as the number input samples.

[100/1296] mean | Random_category | onehot | passthrough | robust → FAILED —
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 613, in fit
    Xt = self._fit(X, y, routed_params, raw_params=params)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 547, in _fit
    X, fitted_transformer = fit_transform_one_cached(
                            ~~~~~~~~~~~~~~~~~~~~~~~~^
        cloned_transformer,
        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        params=step_params,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\joblib\memory.py", line 326, in __call__
    return self.func(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\pipeline.py", line 1484, in _fit_transform_one
    res = transformer.fit_transform(X, y, **params.get("fit_transform", {}))
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1029, in fit_transform
    return self._hstack(list(Xs), n_samples=n_samples)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Vineeth\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\compose\_column_transformer.py", line 1213, in _hstack
    raise ValueError(
    ...<5 lines>...
    )
ValueError: Concatenating DataFrames from the transformer's output lead to an inconsistent number of samples. The output may have Pandas Indexes that do not match, or that transformers are returning number of samples which are not the same as the number input samples.

[101/1296] mean | Random_category | onehot | passthrough | maxabs → FAILED —
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------

ValueError: All arrays must be of the same length

In [2]:
show_results(result_df)

NameError: name 'result_df' is not defined